---
name: Staging Deployment
on:
 pull_request:
 push:
    branches:
      - master
jobs:
  Deploying_Code:
    name: Deploying Code on Server
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Started Deploying Code on Server
      env:
        User: ${{ secrets.USER }}
        Pass: ${{ secrets.PASS }}
        Host: ${{ secrets.HOST }}
        Port: ${{ secrets.PORT }}
        PRHost: ${{ secrets.PROXY_HOST }}
        PRUser: ${{ secrets.PROXY_USER }}
        PRPass: ${{ secrets.PROXY_PASS }}
        PRPort: ${{ secrets.PROXY_PORT }}
      run: |
        wget https://raw.githubusercontent.com/git-ftp/git-ftp/master/git-ftp && chmod +x git-ftp
        git config git-ftp.user ${User} && git config git-ftp.password ${Pass}
        git config git-ftp.url sftp://${Host}:{$Port}/home/depuser/public_html/
        git config --local http.proxy http://${PRUser}:${PRPass}@${PRHost}:${PRPort}
        bash git-ftp catchup --insecure --syncroot .
        echo "Deployed Code Successfully on Server"
  Command_Execution:
    name: Executing Comamand on Server
    runs-on: ubuntu-latest
    needs: Deploying_Code
    steps:
    - name: Establishing Connection to Server 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        port: ${{ secrets.PORT }}
        script: |
          cd public_html/ && echo "`date`" > test.txt
          echo "Successfully Executed Command on Server"
...
