name: Demo Deployment
on:
  push:
    branches: [ master ]

jobs:
  jobs_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Testing Server Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}
        port: ${{ secrets.PORT }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_password: ${{ secrets.PROXY_KEY }}
        proxy_port: ${{ secrets.PORT }}
        script: |
          mkdir hello
          cd hello
          touch a.txt
          ls -lh
