name: Demo Deployment
on:
  push:
    branches: [ master ]

jobs:
  jobs_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Testing Server Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.PASS }}
        port: ${{ secrets.PORT }}
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_username: ${{ secrets.PROXY_USERNAME }}
        proxy_key: ${{ secrets.PROXY_KEY }}
        proxy_port: ${{ secrets.PORT }}
        sync: false
        use_insecure_cipher: false
        proxy_use_insecure_cipher: false
        timeout: 30s
        proxy_timeout: 30s
        command_timeout: 10m
        script_stop: true
        debug: true
        script: |
          mkdir hello
          cd hello
          touch a.txt
          ls -lh
