name: Demo Deployment
on:
  push:
    branches: [ master ]

jobs:
  jobs_one:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Testing Server Connection
      uses: appleboy/ssh-action@master
      with:
        host: 35.154.94.193
        username: depuser
        key: ${{ secrets.DEP_PASSWORD }}
        port: 22
        script: |
          cd /var/www/html
          echo "Helloworld" > test123.txt
